[database]
host = "localhost"
port = "5432"
user = "postgres"
password = "postgres"
db = "btcgifter"
ssl_mode = "disable"
max_conns = 25
min_conns = 5
max_conn_lifetime = 5
max_conn_idle_time = 1

[redis]
host = "localhost"
port = "6379"
password = ""
db = 0

[lnd]
grpc_host = "localhost"
grpc_port = "10009"
tls_cert_path = ""
macaroon_path = ""
network = "testnet"
payment_timeout_seconds = 30
max_payment_fee_sats = 100

[api]
cors_origin = "*"

[qonto]
base_url = "https://thirdparty-sandbox.staging.qonto.co/v2"
login = ""
secret_key = ""
iban = ""

[cryptocom]
base_url = "https://uat-api.3ona.co/exchange/v1/"
api_key = ""
secret_key = ""
http_timeout = 15

[treasury]
lightning_ratio = 1
cryptocom_iban = ""
cryptocom_name = ""
purchase_floor_cents = 1000000
purchase_target_cents = 500000
