package config

type ApiConfig struct {
	Database struct {
		Host            string `toml:"host" env:"BTC_GIFTCARD_DB_HOST"`
		Port            string `toml:"port" env:"BTC_GIFTCARD_DB_PORT" env-default:"5432"`
		User            string `toml:"user" env:"BTC_GIFTCARD_DB_USER"`
		Password        string `toml:"password" env:"BTC_GIFTCARD_DB_PASSWORD"`
		DB              string `toml:"db" env:"BTC_GIFTCARD_DB_NAME"`
		SslMode         string `toml:"ssl_mode" env:"BTC_GIFTCARD_DB_SSL_MODE" env-default:"disable"`
		MaxConns        int    `toml:"max_conns" env:"BTC_GIFTCARD_DB_MAX_CONNS" env-default:"25"`
		MinConns        int    `toml:"min_conns" env:"BTC_GIFTCARD_DB_MIN_CONNS" env-default:"5"`
		MaxConnLifetime int    `toml:"max_conn_lifetime" env:"BTC_GIFTCARD_DB_MAX_CONN_LIFETIME" env-default:"5"`
		MaxConnIdleTime int    `toml:"max_conn_idle_time" env:"BTC_GIFTCARD_DB_MAX_CONN_IDLE_TIME" env-default:"1"`
	} `toml:"database"`

	Redis struct {
		Host     string `toml:"host" env:"BTC_GIFTCARD_REDIS_HOST"`
		Port     string `toml:"port" env:"BTC_GIFTCARD_REDIS_PORT" env-default:"6379"`
		Password string `toml:"password" env:"BTC_GIFTCARD_REDIS_PASSWORD"`
		DB       int    `toml:"db" env:"BTC_GIFTCARD_REDIS_DB" env-default:"0"`
	} `toml:"redis"`

	// LND gRPC connection configuration
	// Used by both the API (for redemptions) and workers (for treasury balance checks)
	LND struct {
		// GRPCHost is the LND gRPC endpoint (e.g., "localhost:10009" or "gift-card-backend.lnd:10009")
		GRPCHost string `toml:"grpc_host" env:"BTC_GIFTCARD_LND_GRPC_HOST"`
		GRPCPort string `toml:"grpc_port" env:"BTC_GIFTCARD_LND_GRPC_PORT" env-default:"10009"`

		// TLSCertPath is the path to LND's tls.cert file for TLS authentication
		// Generated by LND on first start at ~/.lnd/tls.cert
		TLSCertPath string `toml:"tls_cert_path" env:"BTC_GIFTCARD_LND_TLS_CERT_PATH"`

		// MacaroonPath is the path to LND's admin.macaroon for RPC authentication
		// Located at ~/.lnd/data/chain/bitcoin/{network}/admin.macaroon
		// TODO: For production, consider using a more restrictive macaroon
		// (e.g., invoice.macaroon for Lightning-only, or bake a custom one with
		// `lncli bakemacaroon` limiting to: SendPaymentSync, DecodePayReq,
		// WalletBalance, ChannelBalance, SendCoins, NewAddress, GetInfo)
		MacaroonPath string `toml:"macaroon_path" env:"BTC_GIFTCARD_LND_MACAROON_PATH"`

		// Network must match LND's configured network: "mainnet", "testnet", "regtest"
		Network string `toml:"network" env:"BTC_GIFTCARD_LND_NETWORK" env-default:"testnet"`

		// PaymentTimeoutSeconds is the maximum time to wait for a Lightning payment to settle
		PaymentTimeoutSeconds int `toml:"payment_timeout_seconds" env:"BTC_GIFTCARD_LND_PAYMENT_TIMEOUT" env-default:"30"`

		// MaxPaymentFeeSats is the maximum fee (in sats) we're willing to pay for routing a Lightning payment
		// Set to 0 for no limit (not recommended)
		MaxPaymentFeeSats int64 `toml:"max_payment_fee_sats" env:"BTC_GIFTCARD_LND_MAX_FEE_SATS" env-default:"100"`
	} `toml:"lnd"`

	Api struct {
		CorsOrigin string `toml:"cors_origin" env:"BTC_GIFTCARD_CORS_ORIGIN"`
	} `toml:"api"`

	// Qonto banking API — fiat balance monitoring + SEPA transfers
	Qonto struct {
		BaseURL   string `toml:"base_url"    env:"GIFTER_QONTO_BASE_URL"    env-default:"https://thirdparty.qonto.com/v2"`
		Login     string `toml:"login"       env:"GIFTER_QONTO_LOGIN"`
		SecretKey string `toml:"secret_key"  env:"GIFTER_QONTO_SECRET_KEY"`
		IBAN      string `toml:"iban"        env:"GIFTER_QONTO_IBAN"`
	} `toml:"qonto"`

	// CryptoCom exchange API — OTC BTC purchases + withdrawals
	CryptoCom struct {
		BaseURL   string `toml:"base_url"   env:"GIFTER_CRYPTOCOM_BASE_URL"   env-default:"https://api.crypto.com/exchange/v1"`
		APIKey    string `toml:"api_key"    env:"GIFTER_CRYPTOCOM_API_KEY"`
		SecretKey string `toml:"secret_key" env:"GIFTER_CRYPTOCOM_SECRET_KEY"`
	} `toml:"cryptocom"`

	// Treasury controls the automated fiat → BTC → LND pipeline
	Treasury struct {
		// LightningRatio is the fraction of new BTC routed to Lightning channels.
		// The remainder stays in the LND on-chain wallet. Range: [0.0, 1.0].
		LightningRatio float64 `toml:"lightning_ratio"    env:"GIFTER_TREASURY_LIGHTNING_RATIO"    env-default:"0.6"`

		// CryptoComIBAN is the Crypto.com OTC SEPA IBAN (destination of fiat transfers).
		CryptoComIBAN string `toml:"cryptocom_iban"     env:"GIFTER_TREASURY_CRYPTOCOM_IBAN"`

		// CryptoComBeneficiaryName is the legal beneficiary name for SEPA transfers.
		CryptoComBeneficiaryName string `toml:"cryptocom_name"     env:"GIFTER_TREASURY_CRYPTOCOM_NAME"`

		// PurchaseFloorCents — automatic trigger fires when Qonto balance exceeds this (cents).
		// Example: 1_000_000 = 10 000.00 EUR
		PurchaseFloorCents int64 `toml:"purchase_floor_cents"  env:"GIFTER_TREASURY_PURCHASE_FLOOR"  env-default:"1000000"`

		// PurchaseTargetCents — amount to leave in Qonto after an automatic purchase (cents).
		// Example: 500_000 = 5 000.00 EUR
		PurchaseTargetCents int64 `toml:"purchase_target_cents" env:"GIFTER_TREASURY_PURCHASE_TARGET" env-default:"500000"`
	} `toml:"treasury"`
}
