package config

type ApiConfig struct {
	Database struct {
		Host            string `toml:"host" env:"GIFTER_DB_HOST"`
		Port            string `toml:"port" env:"GIFTER_DB_PORT" env-default:"5432"`
		User            string `toml:"user" env:"GIFTER_DB_USER"`
		Password        string `toml:"password" env:"GIFTER_DB_PASSWORD"`
		DB              string `toml:"db" env:"GIFTER_DB_NAME"`
		SslMode         string `toml:"ssl_mode" env:"GIFTER_DB_SSL_MODE" env-default:"disable"`
		MaxConns        int    `toml:"max_conns" env:"GIFTER_DB_MAX_CONNS" env-default:"25"`
		MinConns        int    `toml:"min_conns" env:"GIFTER_DB_MIN_CONNS" env-default:"5"`
		MaxConnLifetime int    `toml:"max_conn_lifetime" env:"GIFTER_DB_MAX_CONN_LIFETIME" env-default:"5"`
		MaxConnIdleTime int    `toml:"max_conn_idle_time" env:"GIFTER_DB_MAX_CONN_IDLE_TIME" env-default:"1"`
	} `toml:"database"`

	Redis struct {
		Host     string `toml:"host" env:"GIFTER_REDIS_HOST"`
		Port     string `toml:"port" env:"GIFTER_REDIS_PORT" env-default:"6379"`
		Password string `toml:"password" env:"GIFTER_REDIS_PASSWORD"`
		DB       int    `toml:"db" env:"GIFTER_REDIS_DB" env-default:"0"`
	} `toml:"redis"`

	// LND gRPC connection configuration
	// Used by both the API (for redemptions) and workers (for treasury balance checks)
	LND struct {
		// GRPCHost is the LND gRPC endpoint (e.g., "localhost:10009" or "gift-card-backend.lnd:10009")
		GRPCHost string `toml:"grpc_host" env:"GIFTER_LND_GRPC_HOST"`
		GRPCPort string `toml:"grpc_port" env:"GIFTER_LND_GRPC_PORT" env-default:"10009"`

		// TLSCertPath is the path to LND's tls.cert file for TLS authentication
		// Generated by LND on first start at ~/.lnd/tls.cert
		TLSCertPath string `toml:"tls_cert_path" env:"GIFTER_LND_TLS_CERT_PATH"`

		// MacaroonPath is the path to LND's admin.macaroon for RPC authentication
		// Located at ~/.lnd/data/chain/bitcoin/{network}/admin.macaroon
		// TODO: For production, consider using a more restrictive macaroon
		// (e.g., invoice.macaroon for Lightning-only, or bake a custom one with
		// `lncli bakemacaroon` limiting to: SendPaymentSync, DecodePayReq,
		// WalletBalance, ChannelBalance, SendCoins, NewAddress, GetInfo)
		MacaroonPath string `toml:"macaroon_path" env:"GIFTER_LND_MACAROON_PATH"`

		// Network must match LND's configured network: "mainnet", "testnet", "regtest"
		Network string `toml:"network" env:"GIFTER_LND_NETWORK" env-default:"testnet"`

		// PaymentTimeoutSeconds is the maximum time to wait for a Lightning payment to settle
		PaymentTimeoutSeconds int `toml:"payment_timeout_seconds" env:"GIFTER_LND_PAYMENT_TIMEOUT" env-default:"30"`

		// MaxPaymentFeeSats is the maximum fee (in sats) we're willing to pay for routing a Lightning payment
		// Set to 0 for no limit (not recommended)
		MaxPaymentFeeSats int64 `toml:"max_payment_fee_sats" env:"GIFTER_LND_MAX_FEE_SATS" env-default:"100"`
	} `toml:"lnd"`

	Api struct {
		CorsOrigin string `toml:"cors_origin" env:"GIFTER_CORS_ORIGIN"`
	} `toml:"api"`

	// Qonto banking API — fiat balance monitoring + SEPA transfers
	Qonto struct {
		BaseURL      string `toml:"base_url"       env:"GIFTER_QONTO_BASE_URL"`
		Login        string `toml:"login"          env:"GIFTER_QONTO_LOGIN"`
		SecretKey    string `toml:"secret_key"     env:"GIFTER_QONTO_SECRET_KEY"`
		IBAN         string `toml:"iban"           env:"GIFTER_QONTO_IBAN"`
		StagingToken string `toml:"staging_token" env:"GIFTER_QONTO_STAGING_TOKEN"`
	} `toml:"qonto"`

	// CryptoCom exchange API — OTC BTC purchases + withdrawals
	CryptoCom struct {
		BaseURL     string `toml:"base_url"   env:"GIFTER_CRYPTOCOM_BASE_URL"`
		APIKey      string `toml:"api_key"    env:"GIFTER_CRYPTOCOM_API_KEY"`
		SecretKey   string `toml:"secret_key" env:"GIFTER_CRYPTOCOM_SECRET_KEY"`
		HTTPTimeout int    `toml:"http_timeout" env:"GIFTER_CRYPTOCOM_HTTP_TIMEOUT"  env-default:"15"`
	} `toml:"cryptocom"`

	// Treasury controls the automated fiat → BTC → LND pipeline
	Treasury struct {
		// CryptoComIBAN is the Crypto.com OTC SEPA IBAN (destination of fiat transfers).
		CryptoComIBAN string `toml:"cryptocom_iban" env:"GIFTER_TREASURY_CRYPTOCOM_IBAN"`

		// CryptoComBeneficiaryName is the legal beneficiary name for SEPA transfers.
		CryptoComBeneficiaryName string `toml:"cryptocom_name" env:"GIFTER_TREASURY_CRYPTOCOM_NAME"`

		// CryptoComBeneficiaryID is the pre-registered Qonto beneficiary UUID for the
		// Crypto.com OTC account. Required for SendTransfer (Qonto v2 API).
		CryptoComBeneficiaryID string `toml:"cryptocom_beneficiary_id" env:"GIFTER_TREASURY_CRYPTOCOM_BENEFICIARY_ID"`

		// PurchaseFloorCents — automatic trigger fires when Qonto balance exceeds this (cents).
		// Example: 1_000_000 = 10 000.00 EUR
		PurchaseFloorCents int64 `toml:"purchase_floor_cents" env:"GIFTER_TREASURY_PURCHASE_FLOOR" env-default:"1000000"`

		// PurchaseTargetCents — amount to leave in Qonto after an automatic purchase (cents).
		// Example: 500_000 = 5 000.00 EUR
		PurchaseTargetCents int64 `toml:"purchase_target_cents" env:"GIFTER_TREASURY_PURCHASE_TARGET" env-default:"500000"`

		// LNDChannelPeerPubKey and LNDChannelPeerHost identify the Lightning peer
		// to open channels with.
		//
		// Production bootstrap:
		//   1. Choose a well-connected routing node as your peer.
		//   2. Open the first channel manually:
		//        lncli connect <pubkey>@<host>
		//        lncli openchannel --node_key <pubkey> --local_amt <sats>
		//   3. Once that channel is live, leave these fields EMPTY — the treasury
		//      worker auto-discovers pubkey and host from ListChannels/ListPeers.
		//
		// Only populate these fields to let the code open channel #1 itself
		// (useful for automated testnet/regtest environments).
		LNDChannelPeerPubKey string `toml:"lnd_channel_peer_pubkey" env:"GIFTER_TREASURY_LND_CHANNEL_PEER_PUBKEY"`
		LNDChannelPeerHost   string `toml:"lnd_channel_peer_host"   env:"GIFTER_TREASURY_LND_CHANNEL_PEER_HOST"`

		// LNDChannelThresholdSats triggers a channel-open when the LND on-chain
		// confirmed balance exceeds this value (satoshis).
		LNDChannelThresholdSats int64 `toml:"lnd_channel_threshold_sats" env:"GIFTER_TREASURY_LND_CHANNEL_THRESHOLD_SATS"`

		// LNDChannelTargetSats is the on-chain balance to keep in LND after opening
		// a channel. Channel size = confirmed_balance - LNDChannelTargetSats.
		LNDChannelTargetSats int64 `toml:"lnd_channel_target_sats" env:"GIFTER_TREASURY_LND_CHANNEL_TARGET_SATS"`
	} `toml:"treasury"`
}
